# Generated by Django 5.2.9 on 2025-12-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_loginpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='senha',
        ),
    ]
